# Generated by Django 5.0.7 on 2024-08-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Imagen",
        ),
    ]
